<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Simple form referencing</description>
   <name>ReferencingForm1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>af1d9cea-a3b2-43ea-88c2-d088f5f20d30</testSuiteGuid>
   <testCaseLink>
      <guid>a6908a0a-b0fe-480a-8fed-93e3a22963df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common/ReferencingSimpleFlowScript</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e0f9c16-2077-4875-b7bb-9c268b20bb4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>974e09a0-ec71-435c-9fd8-253198067a3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>644beb2a-150e-475f-b0f0-8f376c31a456</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e14ad30-9d61-4f61-9edf-db1cc97f5b89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cd1ab40-99d9-4746-899b-394326a61bbd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
