<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Expand_menu_open_instant_insights</name>
   <tag></tag>
   <elementGuidId>8fdd23b2-d8df-4b60-bc1e-2189f5cf603c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='slide-out']/li[8]/a/i/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Redirection to GII - Open Instant Insight&quot;] > i > img.ui.medium.image</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/rportal/modules/custom/srai_materialize_css/images/icons/sales-icon-white.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui medium image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/rportal/modules/custom/srai_materialize_css/images/icons/sales-icon-white.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide-out&quot;)/li[@class=&quot;menu-item&quot;]/a[1]/i[1]/img[@class=&quot;ui medium image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='slide-out']/li[8]/a/i/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/i/img</value>
   </webElementXpaths>
</WebElementEntity>
