<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>datepickerStart</name>
   <tag></tag>
   <elementGuidId>73c4fc38-0c34-4b68-8d7a-e464bd3d2de9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#edit-form-type-start-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#edit-form-type-start-date</value>
      <webElementGuid>6e8a683c-6267-49d7-a0b2-e058a300c727</webElementGuid>
   </webElementProperties>
</WebElementEntity>
