<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>datepickerEnd</name>
   <tag></tag>
   <elementGuidId>d55f047f-79a5-4ad9-a2fc-32e69de94839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#edit-form-type-end-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#edit-form-type-end-date</value>
      <webElementGuid>bebaccda-140b-4878-9aa5-97e487d8fdcf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
