<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemDateStart</name>
   <tag></tag>
   <elementGuidId>7ed7ed5f-3585-4f06-97cf-db38ab435412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='ui-datepicker-div']/table/tbody/tr[${Sweek}]/td[${Sday}]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/table/tbody/tr[${Sweek}]/td[${Sday}]/a</value>
      <webElementGuid>059ddaac-41ed-4a7e-bba8-1d50bec0d9af</webElementGuid>
   </webElementProperties>
</WebElementEntity>
