<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_of_op</name>
   <tag></tag>
   <elementGuidId>c002953a-fdd9-4eea-98dc-2156ef96c661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-create-form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-create-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bbf99ea-a201-4787-a762-8686567c0719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-create-form</value>
      <webElementGuid>10d9852a-e4d6-4777-8efc-04d535e478fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b07c2bed-d768-453e-8e75-9071b2da96e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-create-form</value>
      <webElementGuid>c60d783f-99ba-487f-9222-4447887a3a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>op</value>
      <webElementGuid>2d8ba008-c870-4c29-b785-d67962f7d3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create form</value>
      <webElementGuid>49bd3f9d-0273-432b-ac6f-45dd30fb403b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button js-form-submit form-submit js-show btn</value>
      <webElementGuid>a7b19246-be3b-4e00-b4f7-645cc2f50ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>drupal-ajax</value>
      <webElementGuid>75ffafd1-9669-4b09-a070-6f971525ef60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-create-form&quot;)</value>
      <webElementGuid>ae1b03f5-4be3-41da-b7e0-5cba87f75cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-create-form']</value>
      <webElementGuid>645f2eb4-bb43-4f49-bc7f-499d1f73746b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='supplier-referencing-form-type-list-form']/input</value>
      <webElementGuid>e180d677-8287-4494-9728-ef932c3f38d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>1e5eb2e3-6384-45b2-9f0a-522c8deac9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'edit-create-form' and @name = 'op']</value>
      <webElementGuid>6af7d269-b0b5-4059-8068-b648555dd3e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
