<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_event</name>
   <tag></tag>
   <elementGuidId>1cc2877e-3f29-496a-a999-82da7939f1b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.suffix.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@onclick=&quot;jQuery(this).parent().find('input').focus();&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>37fada3b-d837-41a2-9731-08c999532659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons suffix active</value>
      <webElementGuid>96279da1-5a76-4f46-8d54-833be9f5a19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery(this).parent().find('input').focus();</value>
      <webElementGuid>e4b1029d-e019-49a5-90f9-fc2970a28516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>event</value>
      <webElementGuid>2e3578c8-e94a-4baa-9a42-35e44b7d2939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-form-type-infos&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col s2&quot;]/div[@class=&quot;input-field js-form-item form-item js-form-type-portal-datepicker form-type-portal-datepicker js-form-item-form-type-start-date form-item-form-type-start-date&quot;]/i[@class=&quot;material-icons suffix active&quot;]</value>
      <webElementGuid>f6004d5c-440d-40cf-97c8-2f5d8c119e47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@onclick=&quot;jQuery(this).parent().find('input').focus();&quot;]</value>
      <webElementGuid>30df5f94-6912-4f99-8732-901d70241bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-form-type-infos']/div/div[3]/div/i</value>
      <webElementGuid>7a1d1748-63b8-483f-ac92-2427ffa27821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date'])[1]/following::i[1]</value>
      <webElementGuid>dc4d389c-e273-4302-9311-f98fa2d9353b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::i[1]</value>
      <webElementGuid>07070ed3-51c6-4ae8-8799-620bbeb534ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[1]/preceding::i[1]</value>
      <webElementGuid>45daaa5a-ffd6-4be7-befe-465e91114847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='event'])[2]/preceding::i[1]</value>
      <webElementGuid>dcc287f9-cebf-4d6e-9cb1-757412f3ae9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='event']/parent::*</value>
      <webElementGuid>7c8bd3d8-2491-449d-8058-af70659a863a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>e9fe9de8-bf20-4a06-b2cf-7c8ba1617939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'event' or . = 'event')]</value>
      <webElementGuid>3db58dda-5022-4c00-a635-746c873c599a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
