<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Enable Attributes_lever srai-lever</name>
   <tag></tag>
   <elementGuidId>3bf19973-3e3f-43f7-862f-1f6e530f8386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lever.srai-lever</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-attributes-container']/div/div/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2c41cadc-4ad9-479a-aef2-7e5a8706ebd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lever srai-lever</value>
      <webElementGuid>6f7f00d5-c3ff-4bd3-8c4d-ab9aa2a4491b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-attributes-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col s8&quot;]/div[@class=&quot;js-form-item form-item js-form-type-portal-switch form-type-portal-switch js-form-item-enable-attributes form-item-enable-attributes&quot;]/div[@class=&quot;switch&quot;]/label[1]/span[@class=&quot;lever srai-lever&quot;]</value>
      <webElementGuid>a8be2df8-6d23-426e-b85e-845e9934421f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-attributes-container']/div/div/div/div/label/span</value>
      <webElementGuid>1c8860ef-a70e-47dd-90f4-0e324cb54c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/label/span</value>
      <webElementGuid>6b759548-8fc5-45e6-b17d-6186575f4240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
