<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Enable Service contract_lever srai-lever</name>
   <tag></tag>
   <elementGuidId>8b702a38-b78d-43f5-ab49-28e4d9018a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.js-form-item.form-item.js-form-type-portal-switch.form-type-portal-switch.js-form-item-enable-service-contract.form-item-enable-service-contract > div.switch > label > span.lever.srai-lever</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-service-contract-container']/div/div/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ee4297f-7a9f-41df-96cd-232767c1689c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lever srai-lever</value>
      <webElementGuid>e2e46ba4-9a7c-4bc2-bb57-c86f6ac23d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-service-contract-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col s8&quot;]/div[@class=&quot;js-form-item form-item js-form-type-portal-switch form-type-portal-switch js-form-item-enable-service-contract form-item-enable-service-contract&quot;]/div[@class=&quot;switch&quot;]/label[1]/span[@class=&quot;lever srai-lever&quot;]</value>
      <webElementGuid>3cec4035-5b95-4776-b762-bc47b99d57ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-service-contract-container']/div/div/div/div/label/span</value>
      <webElementGuid>09543115-5b2d-4af8-bb62-137a5d61deb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/label/span</value>
      <webElementGuid>7fe9bdcf-a67b-4187-99aa-864e45296308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
