<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Addresses and Contacts</name>
   <tag></tag>
   <elementGuidId>8d075056-7547-408c-9fd9-b116cbcf4c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-address-contacts > summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//details[@id='edit-address-contacts']/summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>a5c2605c-f9de-46e0-b3ec-55a2ee37e1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c1cc0d0-14a8-4178-8f8e-ea86dece8c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>edit-address-contacts</value>
      <webElementGuid>f3fe0165-7e51-4471-a814-338d61bdda15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac23d676-90d9-4963-aaff-31bc96e10cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b25e27e3-a775-4eda-9d4d-ec609dd7236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Addresses and Contacts</value>
      <webElementGuid>00b9ec33-ea7a-45bd-ba74-e4138c3c2f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-address-contacts&quot;)/summary[1]</value>
      <webElementGuid>8438e44d-0509-4349-8c13-b8dc09336b08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//details[@id='edit-address-contacts']/summary</value>
      <webElementGuid>7ae7f4b0-8be1-41ad-8d3b-91778a477592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[4]/following::summary[1]</value>
      <webElementGuid>bae08382-a929-4774-b0d1-6acf692bbd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[2]/following::summary[1]</value>
      <webElementGuid>9a4cd1cd-ada5-44d8-9195-7a9266e358fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fullscreen'])[3]/preceding::summary[1]</value>
      <webElementGuid>c6dc1435-2122-4db9-8356-e729e7cfcdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Addresses and Contacts']/parent::*</value>
      <webElementGuid>80d178d6-19f3-4e87-bc4f-4976ba633227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[2]/summary</value>
      <webElementGuid>829222ef-e168-4e81-916b-005bcb51c127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = 'Addresses and Contacts' or . = 'Addresses and Contacts')]</value>
      <webElementGuid>01a42911-12b8-476d-9c4c-b6010f9d6f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
