<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Contracts</name>
   <tag></tag>
   <elementGuidId>3b73c3f4-b918-41c4-a277-d30e3f7f8011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-contracts > summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//details[@id='edit-contracts']/summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>08940ee8-bbd1-4b34-8cdf-3a99822fa74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f10b04ab-9cb2-41fc-b625-400adc402d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>edit-contracts</value>
      <webElementGuid>88b2bffa-b145-4b10-a120-e68d650fd7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>20a117b8-4dd6-4e02-98a9-33958230ac4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cbb31f8d-77e0-47e0-a030-bd2117465a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contracts</value>
      <webElementGuid>285a3a0d-4947-4a15-848b-4aea7fdeb4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-contracts&quot;)/summary[1]</value>
      <webElementGuid>d8eb12db-f08b-4b49-85c7-3a7f76c4cf3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//details[@id='edit-contracts']/summary</value>
      <webElementGuid>dbb9c30a-8b4f-49f3-b4f2-5d92fb315164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[8]/following::summary[1]</value>
      <webElementGuid>0e4431cf-afcb-4a9a-8342-4b1772a2c000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[4]/following::summary[1]</value>
      <webElementGuid>11c92eab-c992-497d-8ee1-dc3ca77a50ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fullscreen'])[5]/preceding::summary[1]</value>
      <webElementGuid>d86d65ef-330f-4bfe-8e52-a779f6e98c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[3]/summary</value>
      <webElementGuid>5131d2d6-ad11-4331-aa9c-d37ce480b86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = 'Contracts' or . = 'Contracts')]</value>
      <webElementGuid>75a4c7b8-091a-4942-a7ef-623bbe6bff20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
