<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_General data</name>
   <tag></tag>
   <elementGuidId>f7b1097f-cec6-412f-b00b-795e4686618b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//details[@id='edit-general-data']/summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>77c9c6df-dc8f-491d-bef1-4946a1e7e5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e340b70-5ebc-4c7e-b051-49b391e74c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>edit-general-data</value>
      <webElementGuid>6dc0238e-4d3e-4ac9-b3fb-f1785b69188a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa05ad26-0098-4e22-8e4b-f81f73c42e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aed3e657-6b92-44c0-96ec-517a4e5d0cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General data</value>
      <webElementGuid>2d0163de-a8e6-4d10-9869-6489b066454b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-general-data&quot;)/summary[1]</value>
      <webElementGuid>96ac0c3c-9d94-498c-92e4-f5d91b75b153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//details[@id='edit-general-data']/summary</value>
      <webElementGuid>afb78238-2cab-4593-9fd9-3887497141d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='event'])[2]/following::summary[1]</value>
      <webElementGuid>34afa465-1f86-41be-8cc7-de751c0b5c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[1]/following::summary[1]</value>
      <webElementGuid>24ccaf94-78a1-45a2-889f-4241678edbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fullscreen'])[1]/preceding::summary[1]</value>
      <webElementGuid>8b11be57-9b8c-464d-83c7-41049771f9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[1]/preceding::summary[1]</value>
      <webElementGuid>5709ca10-31d8-4032-84f4-6a342c734965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='General data']/parent::*</value>
      <webElementGuid>e132bf00-d763-40f4-8f3a-7deafc7ad55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//summary</value>
      <webElementGuid>4d5abfe6-0049-43f3-a06b-b3e549eb5468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = 'General data' or . = 'General data')]</value>
      <webElementGuid>86831c25-915d-4ef9-9b7d-ecd519842282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
