<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Validation workflow</name>
   <tag></tag>
   <elementGuidId>967668e4-26fe-4552-8d9f-c60738e8e452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-validation-workflow-container > summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//details[@id='edit-validation-workflow-container']/summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>1b04c3aa-2d9c-4bdd-ad63-73ef20b4d149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2131d547-e0ab-4b00-8009-5362b646124c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>edit-validation-workflow-container</value>
      <webElementGuid>c2950706-54a3-4347-9ecd-321288ce9c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d99e5d21-0292-4c9e-a432-cb17a077ef36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc9a0582-9e87-48fa-a74f-601506ab9685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validation workflow</value>
      <webElementGuid>33933ebd-231a-478e-bb81-42cf5b64b3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-validation-workflow-container&quot;)/summary[1]</value>
      <webElementGuid>0d121248-eb4b-412d-88a7-acddd2a83eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//details[@id='edit-validation-workflow-container']/summary</value>
      <webElementGuid>81a1d188-1333-4d61-bfde-7b29510b37bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You cannot add documents as there are no document entries available. Contact your administator.'])[1]/following::summary[1]</value>
      <webElementGuid>2074b4c2-f6b8-494c-a654-e924eb263cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents'])[1]/following::summary[1]</value>
      <webElementGuid>fe814ac7-9b06-4bd5-b027-4789720807a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fullscreen'])[8]/preceding::summary[1]</value>
      <webElementGuid>d5d74438-f3fc-412f-a1ea-4043e21b3d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[8]/preceding::summary[1]</value>
      <webElementGuid>520db14c-6115-4b2c-8fe3-9b28ef0a9593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Validation workflow']/parent::*</value>
      <webElementGuid>e47d7db7-c2ae-42ab-8a15-1c9fe60a65fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[5]/summary</value>
      <webElementGuid>449f88b7-4645-4695-8474-ab083754f615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = 'Validation workflow' or . = 'Validation workflow')]</value>
      <webElementGuid>5ee5d4fb-edbb-4ed8-974b-5c972ecb2428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
