<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DoubleclickWF</name>
   <tag></tag>
   <elementGuidId>85150db8-e38a-4633-a0bd-5345ddc97cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='users0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#users0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34961dde-6f71-44ad-a1b5-2702c2db9dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>users0</value>
      <webElementGuid>c30656cc-86b2-4da4-8a1f-0bb555212c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-component valign-wrapper</value>
      <webElementGuid>08ae852d-a122-4fc4-9bd2-a8998b8c20af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arrow_drop_down</value>
      <webElementGuid>9158a00f-ed5d-4077-87b1-c86255688970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users0&quot;)</value>
      <webElementGuid>83224cd4-e5e1-4e62-ae04-c28c7c8f29c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='users0']</value>
      <webElementGuid>53f25ccf-6914-4958-99f8-ccccdb15f2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aggrid-validation-workflow-grid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>444c3dab-4511-4f87-90af-ed3f89f7f39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fiber_new'])[1]/following::div[13]</value>
      <webElementGuid>3cc51faf-2864-4344-ab61-0e4b0b01612f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[1]/following::div[26]</value>
      <webElementGuid>39abeb3e-8cb7-4fc2-b96c-ecc942862711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[2]/preceding::div[1]</value>
      <webElementGuid>70a4736a-7374-4b89-8aff-6b4cb1063dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[6]/div/div/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>5c7c5906-4b71-469e-8077-5fbd81d8adf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'users0' and (text() = 'arrow_drop_down' or . = 'arrow_drop_down')]</value>
      <webElementGuid>d014c887-1bec-46fe-ac11-ee3112866c5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
