<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_type_start_date</name>
   <tag></tag>
   <elementGuidId>590437c8-b2c7-4c09-b2db-d246f9dc6db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-form-type-start-date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-form-type-start-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70069e24-e858-41bd-bdb5-8ee38dcbeee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-form-type-start-date</value>
      <webElementGuid>28b062fa-af1c-4ccb-bbc1-96c9c129afbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portal_date_picker form-text required hasDatepicker</value>
      <webElementGuid>a8829713-dc57-45ab-bb15-9751093a1d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1e8aa2d9-b917-4344-ad14-0253409f4532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>default_value</name>
      <type>Main</type>
      <value>2022-11-05</value>
      <webElementGuid>2ebb4b35-3082-40bd-bc2d-36c9ce426e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date_format</name>
      <type>Main</type>
      <value>Y-m-d</value>
      <webElementGuid>ddc58047-2c0d-4b66-ba60-83bfe4d0513c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date_min</name>
      <type>Main</type>
      <value>2022-11-05</value>
      <webElementGuid>570e2e44-940c-4b02-9152-aef087cf9496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-form-type-start-date</value>
      <webElementGuid>88c4c6d4-7e67-44a6-b9ad-9f06dd24e7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_type_start_date</value>
      <webElementGuid>50da309c-b33f-464f-846b-b3705720ef59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-05</value>
      <webElementGuid>ab34aaf0-37d1-475c-ae68-34e09309126c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>14ba61bf-28e8-48f7-a194-3994ec61e9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aaf77891-b4c1-46bf-b22d-24aae7b99890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>111076ab-5472-4819-8d5c-d1076176a0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-form-type-start-date&quot;)</value>
      <webElementGuid>7f837db0-0783-4a09-9160-681609a90c2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-form-type-start-date']</value>
      <webElementGuid>cd094fc1-9e55-470b-98fe-4d5b5994dbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-form-type-infos']/div/div[3]/div/input</value>
      <webElementGuid>18698bfe-d041-4750-a9c2-006ccfc7a2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0c6b9c49-635f-4f14-9be8-4b677ecdc9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edit-form-type-start-date' and @name = 'form_type_start_date']</value>
      <webElementGuid>bd4bd514-1eaa-4f56-8235-c944003739cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
