<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_type_end_date</name>
   <tag></tag>
   <elementGuidId>4be32d97-cf4b-428f-8140-0da9ad4851e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-form-type-end-date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-form-type-end-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13fcda1d-7a4d-447c-a2de-69c0d94957f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-form-type-end-date</value>
      <webElementGuid>d327a5a9-2392-4b96-9bb3-242fcea863ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portal_date_picker form-text required hasDatepicker</value>
      <webElementGuid>d4f21371-f601-4dd3-84ca-6fbfac61efb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b8e8354d-98fe-48e6-ba2c-c5d9b6e6fe92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date_format</name>
      <type>Main</type>
      <value>Y-m-d</value>
      <webElementGuid>82794344-d08d-4e44-a202-0ffdbe89d14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date_min</name>
      <type>Main</type>
      <value>2022-11-05</value>
      <webElementGuid>acb22c67-1a77-4ffc-a725-c45284cbe0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-form-type-end-date</value>
      <webElementGuid>9f52577d-966c-4942-99a7-0490ff7d7eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_type_end_date</value>
      <webElementGuid>f663625a-886a-431e-99ce-6b59f02e5599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>86f028ec-6545-4de7-892c-ada31c2fac18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac1ec565-f0eb-42f7-b5e0-9f5cdc07db9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e2003474-d90e-4613-9e16-40161ae042d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-form-type-end-date&quot;)</value>
      <webElementGuid>65f50cd6-7e74-4d07-bc45-c8eb75e4ecd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-form-type-end-date']</value>
      <webElementGuid>be0b80c2-60c3-4b31-99d9-5246cfdc1b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-form-type-infos']/div/div[4]/div/input</value>
      <webElementGuid>bffd7164-be89-4fc7-8702-d4405639f1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>f24f192d-a0d0-446d-91ee-fc3fc49ea346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edit-form-type-end-date' and @name = 'form_type_end_date']</value>
      <webElementGuid>fc0c3b99-b3b7-42bd-9a11-74c906890009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
