<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveButtonWF</name>
   <tag></tag>
   <elementGuidId>2e23a126-2faa-47f9-b784-6089a7fdc59e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffbed6bb-8577-47d3-b970-0ff6915ce5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-save</value>
      <webElementGuid>00259e6a-7252-4066-b887-dbdecb84a6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>72158dbe-ae01-4bbe-94d3-17d4689191e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-save</value>
      <webElementGuid>94be7eea-e640-4961-9752-7f1d94cd2a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>op</value>
      <webElementGuid>51f17320-e116-46ff-bd2c-926c992198b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>02c41c94-8d4b-461e-bd7d-e9b2e609d434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button js-form-submit form-submit js-show btn</value>
      <webElementGuid>7ab5fb16-19a5-4670-8184-8c07885ee888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>drupal-ajax</value>
      <webElementGuid>48605637-47e8-4219-86ee-d5a9ab8da950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-save&quot;)</value>
      <webElementGuid>616b2e57-d3bc-40fc-89ad-ef6d9886b81c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-save']</value>
      <webElementGuid>72343d52-e574-4ea4-974f-40aaf9584cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='supplier-referencing-form-type-manager-form']/input</value>
      <webElementGuid>629c98d0-4168-4ecc-b5bd-6c3405dc7477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>1ef81b6e-5103-48f9-ac12-153f4bce2571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'edit-save' and @name = 'op']</value>
      <webElementGuid>0f4a9743-dc57-4390-ae03-d251010f6455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
