<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectUsersWF</name>
   <tag></tag>
   <elementGuidId>9b05d54d-8418-448c-823b-2faae3432216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aggrid-validation-workflow-grid']/div/div[6]/div/div/div/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'portal_manager1@retailer.local' or . = 'portal_manager1@retailer.local')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.result-selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5e5e5190-9157-4593-86e6-9f7ead1f0d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result-selected</value>
      <webElementGuid>9ba9e477-410c-46d8-ab33-6a1bd1eebfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>94426d19-ae3e-48c6-8501-9c47cf4da54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>portal_manager1@retailer.local</value>
      <webElementGuid>8e50f81c-76c4-4a67-9f26-483cd1fad19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aggrid-validation-workflow-grid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-auto-height ag-ltr&quot;]/div[@class=&quot;ag-theme-balham ag-popup&quot;]/div[@class=&quot;ag-popup-editor ag-ltr ag-popup-child aggrid-select&quot;]/div[@class=&quot;container-select&quot;]/div[@class=&quot;chosen-container chosen-container-multi chosen-with-drop chosen-container-active&quot;]/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;result-selected&quot;]</value>
      <webElementGuid>fcbe529a-169c-4774-baf5-e7c474b1b66a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aggrid-validation-workflow-grid']/div/div[6]/div/div/div/div/ul/li[3]</value>
      <webElementGuid>13ff7e82-7315-44d3-b948-ba7f6a4d8c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='portal_admin@retailer.local'])[2]/following::li[1]</value>
      <webElementGuid>f01ba75a-3092-4e3f-9d10-2e65bacc7434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='technical_admin@retailer.local'])[2]/following::li[2]</value>
      <webElementGuid>06fff6ad-557d-455f-b535-3c4325a42657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='portal_manager2@retailer.local'])[2]/preceding::li[1]</value>
      <webElementGuid>f1ed41c6-ec24-4507-9b3d-0b064e10f68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='portal_manager3@retailer.local'])[2]/preceding::li[2]</value>
      <webElementGuid>05f00921-80b9-4721-b3d3-9d61d8468db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>818ab630-79ed-410c-9ccb-9a214b279375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'portal_manager1@retailer.local' or . = 'portal_manager1@retailer.local')]</value>
      <webElementGuid>b907bca9-aa79-4c92-8f99-c2b60c434103</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
