<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Contracts</name>
   <tag></tag>
   <elementGuidId>7ae55403-1ba0-4bcb-9178-4995c5f6fb19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-contracts > summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//details[@id='edit-contracts']/summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>8235a282-c0f6-4142-9556-0630ac5dea9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a331a002-8de8-42fd-86b3-e6e8caf5479e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>edit-contracts</value>
      <webElementGuid>3373b89f-b950-4951-814f-5915a5690518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21136ff9-d228-4fde-8c60-0e604d061951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>576f9a31-1dd3-46d2-b419-ac96d684c733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contracts</value>
      <webElementGuid>6b344e21-b49d-43ff-b14f-ce0889c5bd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-contracts&quot;)/summary[1]</value>
      <webElementGuid>9815a0c2-bd88-4f62-bd2a-152956329b5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//details[@id='edit-contracts']/summary</value>
      <webElementGuid>e579f750-fead-4827-a604-6185c8ab47cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[10]/following::summary[1]</value>
      <webElementGuid>7e72fd8f-5c92-42c6-a71a-c494d03b9a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[5]/following::summary[1]</value>
      <webElementGuid>9387e7fb-d3e3-4b88-a798-10824bdfbe5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fullscreen'])[6]/preceding::summary[1]</value>
      <webElementGuid>c89db8f0-b1fe-4c4e-8248-b99e8325cdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[4]/summary</value>
      <webElementGuid>1593c19f-fdc4-48ad-ba18-ec40a8453811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = 'Contracts' or . = 'Contracts')]</value>
      <webElementGuid>6f8e1ed9-6a82-4e21-bf2c-df3ea4fff9ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
