<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserWorkflow</name>
   <tag></tag>
   <elementGuidId>a89fb658-4807-4c72-a08a-7aaf5497790d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='users0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#users0 > span.select-value.truncate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6ac76ab7-0932-466e-b152-36ce73033e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-value truncate</value>
      <webElementGuid>b110235b-2cac-4714-a900-5689e968b40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>portal_admin@retailer.local</value>
      <webElementGuid>9f2d5470-3a51-4b7a-959d-0855a372ff2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users0&quot;)/span[@class=&quot;select-value truncate&quot;]</value>
      <webElementGuid>afefc375-3098-4d2e-9434-0c7d078c1a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='users0']/span</value>
      <webElementGuid>fe1fc389-08e0-42a6-b108-f3a63ac24ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fiber_new'])[4]/following::span[2]</value>
      <webElementGuid>afa24423-6215-438e-a211-6d7467912c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notify'])[1]/following::span[14]</value>
      <webElementGuid>82c64ea2-b004-4cbd-be25-78eae0ab0b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[3]/preceding::span[1]</value>
      <webElementGuid>885d76ad-bf3c-4505-a402-6c1d6c864b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[4]/preceding::span[3]</value>
      <webElementGuid>6dc86dd7-9646-450f-bced-58a58b9db0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='portal_admin@retailer.local']/parent::*</value>
      <webElementGuid>fd9eaedd-18b9-4717-b4c0-37c87197178a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div[3]/div/span</value>
      <webElementGuid>04a55324-55dd-4d10-aa37-f0f79a40fe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'portal_admin@retailer.local' or . = 'portal_admin@retailer.local')]</value>
      <webElementGuid>a280827d-f348-4767-8a8e-15b72b47cd80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
