<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End date_form_type_end_date</name>
   <tag></tag>
   <elementGuidId>713dcfda-54ce-42b3-9a8e-9251890a9329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-form-type-end-date']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'edit-form-type-end-date' and @name = 'form_type_end_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-form-type-end-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>242a3229-ecc6-4304-96d8-15da3317476c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-form-type-end-date</value>
      <webElementGuid>8665074f-7a11-46d3-809c-d9b88b72f3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portal_date_picker form-text required hasDatepicker</value>
      <webElementGuid>7bc6bea0-cd07-498e-bb77-ff0506ca1c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1166ab7c-83b4-4a24-8c86-787742b5a962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date_format</name>
      <type>Main</type>
      <value>Y-m-d</value>
      <webElementGuid>916af722-be4d-4e23-9556-79e7e66749dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date_min</name>
      <type>Main</type>
      <value>2022-11-12</value>
      <webElementGuid>53635899-89f2-4d29-a19d-20a8af955c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-form-type-end-date</value>
      <webElementGuid>ac5cca2d-5fda-4454-bf1f-cbbfed1d4495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_type_end_date</value>
      <webElementGuid>0fd88fcf-5c47-4ea2-aac6-6bedf9a274c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>1f01eb19-4c4e-4c6f-b5af-31035fd23106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c6fd675d-d35c-4e6c-997d-a4c7fe6d3c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0193e620-c878-432f-8626-506b73980351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-form-type-end-date&quot;)</value>
      <webElementGuid>11cd8c8e-36f4-42c0-bd01-574ef88d3301</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-form-type-end-date']</value>
      <webElementGuid>818d4a45-eea8-4863-a64f-8938c8ad5abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-form-type-infos']/div/div[4]/div/input</value>
      <webElementGuid>56bbc713-046d-4dca-ae13-3fbbfb500122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>590a72fa-d399-4bca-8c99-e66280e5b99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edit-form-type-end-date' and @name = 'form_type_end_date']</value>
      <webElementGuid>5c71b439-0afa-4ec1-93b5-ace70067fcd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
