<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start date_form_type_start_date</name>
   <tag></tag>
   <elementGuidId>4c779804-9b86-43d4-84aa-ddfae4581e5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-form-type-start-date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-form-type-start-date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fed0d4bd-d783-45d7-be49-dc440c0ba0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-form-type-start-date</value>
      <webElementGuid>857b4ce6-7f2c-49ec-814e-680c14b9ddb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portal_date_picker form-text required hasDatepicker</value>
      <webElementGuid>0081746e-659e-4a20-9985-d39fd3d2bc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>18092090-94e1-4568-bddd-afb42241ee4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>default_value</name>
      <type>Main</type>
      <value>2022-11-05</value>
      <webElementGuid>c049879a-be46-48c1-808e-68b858ceea2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date_format</name>
      <type>Main</type>
      <value>Y-m-d</value>
      <webElementGuid>5f8f7812-bfbf-4e6d-b7a7-79417f451c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date_min</name>
      <type>Main</type>
      <value>2022-11-05</value>
      <webElementGuid>014d7a3a-9713-4ce2-a497-38d5d786b3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-form-type-start-date</value>
      <webElementGuid>aa4ac03c-a366-4da8-ab4e-a700a7bf389f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_type_start_date</value>
      <webElementGuid>b4f6d613-66a8-4820-9088-bca5b95817b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-05</value>
      <webElementGuid>a4138376-4e9c-4d56-b1b7-4616a84b5293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b6ae5793-bc32-44d2-8dc2-bd121252e96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f55e5106-06ec-490a-b1fa-34e2392f8895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9bc1964e-f595-44d5-8971-e980de2a21c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-form-type-start-date&quot;)</value>
      <webElementGuid>b0f0eeba-f5cf-43e9-a5a8-195e89054c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-form-type-start-date']</value>
      <webElementGuid>6c2a35c1-ee92-46ec-9cf9-bd9352e4c65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-form-type-infos']/div/div[3]/div/input</value>
      <webElementGuid>cb7f8ad6-ac4f-4914-88b7-f1175a904c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>56cd6392-5af6-4d4c-9a62-e2a07176287e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edit-form-type-start-date' and @name = 'form_type_start_date']</value>
      <webElementGuid>370958b4-1d12-4ef9-9bf7-ea86ed2de2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
